generator:
  class: sfPropelGenerator
  param:
    model_class:           PcBookkeepingContact
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              PcBookkeepingContact
    plural:                PcBookkeepingContacts
    route_prefix:          pc_bookkeeping_contact
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
